/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'mywebui_scada_engine.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./mywebui_scada_engine.android-arm64.node')
          } else {
            nativeBinding = require('mywebui_scada_engine-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'mywebui_scada_engine.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./mywebui_scada_engine.android-arm-eabi.node')
          } else {
            nativeBinding = require('mywebui_scada_engine-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'mywebui_scada_engine.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mywebui_scada_engine.win32-x64-msvc.node')
          } else {
            nativeBinding = require('mywebui_scada_engine-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'mywebui_scada_engine.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mywebui_scada_engine.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('mywebui_scada_engine-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'mywebui_scada_engine.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mywebui_scada_engine.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('mywebui_scada_engine-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'mywebui_scada_engine.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./mywebui_scada_engine.darwin-universal.node')
      } else {
        nativeBinding = require('mywebui_scada_engine-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'mywebui_scada_engine.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./mywebui_scada_engine.darwin-x64.node')
          } else {
            nativeBinding = require('mywebui_scada_engine-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'mywebui_scada_engine.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mywebui_scada_engine.darwin-arm64.node')
          } else {
            nativeBinding = require('mywebui_scada_engine-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'mywebui_scada_engine.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./mywebui_scada_engine.freebsd-x64.node')
      } else {
        nativeBinding = require('mywebui_scada_engine-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'mywebui_scada_engine.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mywebui_scada_engine.linux-x64-musl.node')
            } else {
              nativeBinding = require('mywebui_scada_engine-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'mywebui_scada_engine.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mywebui_scada_engine.linux-x64-gnu.node')
            } else {
              nativeBinding = require('mywebui_scada_engine-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'mywebui_scada_engine.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mywebui_scada_engine.linux-arm64-musl.node')
            } else {
              nativeBinding = require('mywebui_scada_engine-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'mywebui_scada_engine.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mywebui_scada_engine.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('mywebui_scada_engine-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'mywebui_scada_engine.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mywebui_scada_engine.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('mywebui_scada_engine-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'mywebui_scada_engine.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mywebui_scada_engine.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('mywebui_scada_engine-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'mywebui_scada_engine.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mywebui_scada_engine.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('mywebui_scada_engine-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'mywebui_scada_engine.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./mywebui_scada_engine.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('mywebui_scada_engine-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'mywebui_scada_engine.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./mywebui_scada_engine.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('mywebui_scada_engine-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { version, ping, hardware_id, activation_request, validate_license, handle_demo, demo_host_roundtrip, create_importmap, upload_widgets, audit_usage, resolve_screen_access, resolve_visibility, resolve_sec_write } = nativeBinding

module.exports.version = version
module.exports.ping = ping
module.exports.hardware_id = hardware_id
module.exports.activation_request = activation_request
module.exports.validate_license = validate_license
module.exports.handle_demo = handle_demo
module.exports.demo_host_roundtrip = demo_host_roundtrip
module.exports.create_importmap = create_importmap
module.exports.upload_widgets = upload_widgets
module.exports.audit_usage = audit_usage
module.exports.resolve_screen_access = resolve_screen_access
module.exports.resolve_visibility = resolve_visibility
module.exports.resolve_sec_write = resolve_sec_write
